# Generated by Django 4.2.5 on 2023-10-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_conversationhistory_llm_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscribedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='audio_files/')),
                ('transcribed_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
